development:
  adapter: postgresql
  encoding: unicode
  database: cla2015_development
  pool: 5
  host: localhost
  
test:
  adapter: postgresql
  encoding: unicode
  database: cla2015_test
  pool: 5
  